function [difference, starts, ends] = import_datapassing_timings()
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/travis/Dropbox/PHD/MATLAB-Dataflow/DataPassingTimes.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/05/09 13:25:09

%% Initialize variables.
filename = '/home/travis/Dropbox/PHD/MATLAB-Dataflow/DataPassingTimes.txt';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%5f%20f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
difference = dataArray{:, 1};
starts = dataArray{:, 2};
ends = dataArray{:, 3};


%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;