test:
	g++-4.8 -std=c++11 testFlowMP.cpp -lboost_thread -lboost_system -lstdc++ -lm -I../ -I../include -I../src -o testExec

testBoost1_49:
	g++ -std=c++11 -lboost_thread -lboost_system -I../include -I../src -I../boost_1_49_0/stage/lib -I../boost_1_49_0/boost testFlowMP.cpp -o testExec -v
